### ISSUE TITLE
[Request] Please add option "merge-ouput-format" to "All settings"

### ISSUE THREAD

**Issue by black-ish** [Thomasedv/Grabber#11]
As title says.

**Comment by Thomasedv** [comment]
I've uploaded a test build with the option added: https://github.com/Thomasedv/Grabber/releases/tag/V4.0-alpha

I've changed computer and dev enviroment, as well as made some larger changes behind the scenes in the way the settings and profiles are stored and structured, so it's a bit untested build overall (but works on my end at least). Not that i get to test much to begin with....

Download the new executable and replace the old one with it and see what happens... If all goes well you should have the option there.

If you have any other feedback or problems, don't hesitate to make an issue for it.

**Comment by black-ish** [comment]
Thank you very much. I'm going to check if I encounter any bugs and will report them if I find them.

**Comment by Thomasedv** [comment]
Thanks a lot. Report back here if you get it to work, and i can set my first issue to closed!

**Comment by black-ish** [comment]
After a few tests it seems to work without any problems.
In use is ""--format" "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio"" with ""--merge-output-format" "mp4"" and "--add-metadata"
Works really well. Also tried mkv and ofc it also works.
Can be closed.

**Comment by Thomasedv** [comment]
Good to hear. Happy to know it started without issue. (due to other changes behind the scenes)
Appreciate the feedback!
